//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Messages {
        
        /// <summary>
        ///   Looks up a localized string similar to: You did not specify {0}!
        /// </summary>
        public static string RequiredValidationErrorMessage(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.RequiredValidationErrorMessage, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::Resources.Messages.ResourceManager.GetString("RequiredValidationErrorMessage", resourceCulture), System.Tuple.Create("0", arg0));
        }
    }
}
namespace Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MessagesKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: You did not specify {0}!
        /// </summary>
        public const string RequiredValidationErrorMessage = "RequiredValidationErrorMessage";
    }
}
