//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace Resources.Models.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class User {
        
        /// <summary>
        ///   Looks up a localized string similar to: Email Address
        /// </summary>
        public static string EmailAddress([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.User.EmailAddress;
            }
            return global::Resources.Models.User.ResourceManager.GetString("EmailAddress", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Password
        /// </summary>
        public static string Password([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.User.Password;
            }
            return global::Resources.Models.User.ResourceManager.GetString("Password", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Username
        /// </summary>
        public static string Username([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::Resources.Models.User.Username;
            }
            return global::Resources.Models.User.ResourceManager.GetString("Username", resourceCulture);
        }
    }
}
namespace Resources.Models.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class UserKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Email Address
        /// </summary>
        public const string EmailAddress = "EmailAddress";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Password
        /// </summary>
        public const string Password = "Password";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Username
        /// </summary>
        public const string Username = "Username";
    }
}
